### ISSUE TITLE
"resolution" setting in the display_models.json file

### ISSUE THREAD

**Issue by KailynnnWuuu** [gfxdisp/ColorVideoVDP#17]
In the display_models.json file, I would like to confirm whether the "resolution" parameter refers to the monitor's physical resolution or the image resolution. For instance, if an image with a resolution of 1920x1440 is displayed across half of a monitor with a 4K resolution, how should the "resolution" be set in the display_models.json file?

**Comment by mantiuk** [comment]
The resolution refers to the display resolution, not the resolution of the content. It is explained in more detail in:

https://github.com/gfxdisp/ColorVideoVDP?tab=readme-ov-file#display-specification

**Comment by KailynnnWuuu** [comment]
oh! thk!
